# Generated by Django 4.1.2 on 2022-10-11 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 13, 31, 35, 796036, tzinfo=datetime.timezone.utc), verbose_name='заказ создан'),
        ),
    ]
