# Generated by Django 4.1.2 on 2022-10-11 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='обьект создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='обьект изменен')),
                ('title', models.CharField(max_length=150, verbose_name='Название бренда')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='обьект создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='обьект изменен')),
                ('title', models.CharField(max_length=50, verbose_name='Название цвета')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='обьект создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='обьект изменен')),
                ('title', models.CharField(max_length=150, verbose_name='Название модели')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='заказ создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='заказ изменен')),
                ('ordered_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.car_brand', verbose_name='Бренд машины')),
                ('ordered_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.car_color', verbose_name='Выбранный цвет')),
                ('ordered_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.car_model', verbose_name='Модель машины')),
            ],
        ),
    ]
